export const themes = {
  light: {
    cream: "#f9f6f0",
    warmWhite: "#fdfaf5",
    ink: "#2c2416",
    softInk: "#4a3f2f",
    muted: "#8a7a65",
    accent: "#7a5c3a",
    accentLight: "#c4a882",
    rule: "#d9cfc0",
    sage: "#5a8a6a",
    sageBg: "#f0f5f2",
    warnBg: "#fff8f0",
    warnBorder: "#c4824a",
    faithBg: "#f5f0f8",
  },
  dark: {
    cream: "#1a1612",
    warmWhite: "#241f1a",
    ink: "#f9f6f0",
    softInk: "#d9cfc0",
    muted: "#8a7a65",
    accent: "#c4a882",
    accentLight: "#7a5c3a",
    rule: "#3d352b",
    sage: "#7db38e",
    sageBg: "#1e2a22",
    warnBg: "#2a1e14",
    warnBorder: "#c4824a",
    faithBg: "#241a2a",
  }
};

export const font = {
  serif: "'Cormorant Garamond', Georgia, serif",
  sans: "'Lato', system-ui, sans-serif",
};

export const getStyles = (C) => ({
  app: {
    fontFamily: font.sans,
    background: C.cream,
    minHeight: "100vh",
    maxWidth: 480,
    margin: "0 auto",
    position: "relative",
    paddingBottom: 80,
    color: C.ink,
    transition: "background 0.3s, color 0.3s",
  },
  header: {
    background: C.ink,
    color: C.cream,
    padding: "20px 24px 16px",
    position: "sticky",
    top: 0,
    zIndex: 10,
    transition: "background 0.3s, color 0.3s",
  },
  headerTitle: {
    fontFamily: font.serif,
    fontSize: 22,
    fontWeight: 400,
    letterSpacing: 0.5,
    margin: 0,
  },
  headerSub: {
    fontSize: 11,
    color: C.accentLight,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginTop: 2,
  },
  nav: {
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 480,
    background: C.ink,
    display: "flex",
    borderTop: `2px solid ${C.accent}`,
    zIndex: 20,
    transition: "background 0.3s",
  },
  navBtn: (active) => ({
    flex: 1,
    padding: "10px 4px 8px",
    background: "none",
    border: "none",
    cursor: "pointer",
    color: active ? C.accentLight : C.muted,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: font.sans,
    transition: "color 0.2s",
  }),
  page: { padding: "24px 20px" },
  h1: {
    fontFamily: font.serif,
    fontSize: 28,
    fontWeight: 400,
    color: C.ink,
    marginBottom: 6,
    lineHeight: 1.2,
  },
  h2: {
    fontFamily: font.serif,
    fontSize: 20,
    fontWeight: 500,
    color: C.accent,
    marginBottom: 10,
    marginTop: 24,
  },
  p: { color: C.softInk, lineHeight: 1.7, marginBottom: 12, fontSize: 15 },
  card: {
    background: C.warmWhite,
    border: `1px solid ${C.rule}`,
    borderRadius: 8,
    padding: "16px 18px",
    marginBottom: 12,
    transition: "background 0.3s, border-color 0.3s",
  },
  warnBox: {
    background: C.warnBg,
    borderLeft: `4px solid ${C.warnBorder}`,
    borderRadius: "0 6px 6px 0",
    padding: "14px 16px",
    marginBottom: 16,
  },
  safeBox: {
    background: C.sageBg,
    borderLeft: `4px solid ${C.sage}`,
    borderRadius: "0 6px 6px 0",
    padding: "14px 16px",
    marginBottom: 16,
  },
  label: {
    fontSize: 10,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontWeight: 700,
    color: C.muted,
    marginBottom: 6,
    display: "block",
  },
  pill: (color, bg) => ({
    display: "inline-block",
    background: bg,
    color: color,
    borderRadius: 20,
    padding: "3px 12px",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
  }),
  btn: (variant = "primary") => ({
    background: variant === "primary" ? C.ink : "transparent",
    color: variant === "primary" ? C.cream : C.accent,
    border: variant === "primary" ? "none" : `1px solid ${C.accent}`,
    borderRadius: 6,
    padding: "10px 20px",
    fontFamily: font.sans,
    fontSize: 14,
    cursor: "pointer",
    letterSpacing: 0.5,
    transition: "all 0.2s",
  }),
  input: {
    width: "100%",
    background: C.warmWhite,
    border: `1px solid ${C.rule}`,
    borderRadius: 6,
    padding: "10px 12px",
    fontFamily: font.sans,
    fontSize: 14,
    color: C.ink,
    marginBottom: 10,
    boxSizing: "border-box",
    resize: "vertical",
    transition: "background 0.3s, border-color 0.3s, color 0.3s",
  },
  divider: {
    border: "none",
    borderTop: `1px solid ${C.rule}`,
    margin: "20px 0",
  },
});

// For backward compatibility and initial load
export const C = themes.light;
export const s = getStyles(C);
