export const themes = {
  light: {
    cream: "#f9f6f0",
    warmWhite: "#fdfaf5",
    ink: "#2c2416",
    softInk: "#4a3f2f",
    muted: "#8a7a65",
    accent: "#7a5c3a",
    accentLight: "#c4a882",
    rule: "#d9cfc0",
    sage: "#5a8a6a",
    sageBg: "#f0f5f2",
    warnBg: "#fff8f0",
    warnBorder: "#c4824a",
    faithBg: "#f5f0f8",
  },
  dark: {
    cream: "#1a1612",
    warmWhite: "#241f1a",
    ink: "#f9f6f0",
    softInk: "#d9cfc0",
    muted: "#8a7a65",
    accent: "#c4a882",
    accentLight: "#7a5c3a",
    rule: "#3d352b",
    sage: "#7db38e",
    sageBg: "#1e2a22",
    warnBg: "#2a1e14",
    warnBorder: "#c4824a",
    faithBg: "#241a2a",
  }
};

export const font = {
  serif: "'Cormorant Garamond', Georgia, serif",
  sans: "'Lato', system-ui, sans-serif",
};

export const getStyles = (C) => ({
  app: {
    fontFamily: font.sans,
    background: C.cream,
    minHeight: "100vh",
    width: "100%",
    maxWidth: "none",
    margin: 0,
    position: "relative",
    paddingBottom: 0,
    color: C.ink,
    transition: "background 0.3s, color 0.3s",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    background: C.ink,
    color: C.cream,
    padding: "24px clamp(20px, 4vw, 56px) 20px",
    position: "relative",
    zIndex: 10,
    transition: "background 0.3s, color 0.3s",
  },
  headerTitle: {
    fontFamily: font.serif,
    fontSize: 26,
    fontWeight: 400,
    letterSpacing: 0.5,
    margin: 0,
  },
  headerSub: {
    fontSize: 12,
    color: C.accentLight,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginTop: 4,
  },
  nav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    width: "100%",
    maxWidth: "none",
    background: C.ink,
    display: "flex",
    borderTop: `2px solid ${C.accent}`,
    zIndex: 20,
    transition: "background 0.3s",
  },
  navBtn: (active) => ({
    flex: 1,
    padding: "12px 4px 10px",
    background: "none",
    border: "none",
    cursor: "pointer",
    color: active ? C.accentLight : C.muted,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: font.sans,
    transition: "color 0.2s",
  }),
  page: { 
    padding: "clamp(28px, 4vw, 56px) 0",
    maxWidth: "none",
    margin: "0",
    width: "100%",
  },
  h1: {
    fontFamily: font.serif,
    fontSize: 32,
    fontWeight: 400,
    color: C.ink,
    marginBottom: 8,
    lineHeight: 1.2,
  },
  h2: {
    fontFamily: font.serif,
    fontSize: 22,
    fontWeight: 500,
    color: C.accent,
    marginBottom: 12,
    marginTop: 28,
  },
  p: { color: C.softInk, lineHeight: 1.8, marginBottom: 14, fontSize: 16 },
  card: {
    background: C.warmWhite,
    border: `1px solid ${C.rule}`,
    borderRadius: 12,
    padding: "20px 24px",
    marginBottom: 16,
    transition: "background 0.3s, border-color 0.3s",
  },
  warnBox: {
    background: C.warnBg,
    borderLeft: `4px solid ${C.warnBorder}`,
    borderRadius: "0 8px 8px 0",
    padding: "16px 20px",
    marginBottom: 20,
  },
  safeBox: {
    background: C.sageBg,
    borderLeft: `4px solid ${C.sage}`,
    borderRadius: "0 8px 8px 0",
    padding: "16px 20px",
    marginBottom: 20,
  },
  label: {
    fontSize: 11,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontWeight: 700,
    color: C.muted,
    marginBottom: 8,
    display: "block",
  },
  pill: (color, bg) => ({
    display: "inline-block",
    background: bg,
    color: color,
    borderRadius: 20,
    padding: "4px 14px",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0.5,
  }),
  btn: (variant = "primary") => ({
    background: variant === "primary" ? C.ink : "transparent",
    color: variant === "primary" ? C.cream : C.accent,
    border: variant === "primary" ? "none" : `1px solid ${C.accent}`,
    borderRadius: 8,
    padding: "12px 24px",
    fontFamily: font.sans,
    fontSize: 15,
    cursor: "pointer",
    letterSpacing: 0.5,
    transition: "all 0.2s",
    fontWeight: 600,
  }),
  input: {
    width: "100%",
    background: C.warmWhite,
    border: `1px solid ${C.rule}`,
    borderRadius: 8,
    padding: "12px 16px",
    fontFamily: font.sans,
    fontSize: 15,
    color: C.ink,
    marginBottom: 12,
    boxSizing: "border-box",
    resize: "vertical",
    transition: "background 0.3s, border-color 0.3s, color 0.3s",
  },
  divider: {
    border: "none",
    borderTop: `1px solid ${C.rule}`,
    margin: "24px 0",
  },
  stepProgress: {
    display: "flex",
    gap: 4,
    marginBottom: 24,
    justifyContent: "center",
  },
  stepDot: (active, completed) => ({
    width: 32,
    height: 6,
    borderRadius: 3,
    background: active ? C.accent : completed ? C.sage : C.rule,
    transition: "all 0.3s",
  }),
});

export const C = themes.light;
export const s = getStyles(C);
